### ISSUE TITLE
Support /_search

### ISSUE THREAD

**Issue by dawnerd** [stagebloc/local-theme-dev#16]
Trying to use the search endpoint but it doesn't seem to work.

Example code:

```js
$.ajax({
    method: 'post',
    type: 'json',
    data: {
      q: 'something',
      offset: 0,
      limit: 10
    },
    url: '/_search',
    success: function(data) {
      console.log(data);
    }
  });
```

Instead of the expected json response I get the main html.

**Comment by joshholat** [comment]
@dawnerd One thing is that there is a required `filter` parameter. I think that's missing from the docs, I can fix that. @jdhartley and I can get this added to the local theme dev, but for now passing `filter: "audio_playlists"` in your `data

**Comment by dawnerd** [comment]
Awesome, I'll give that a shot.

**Comment by CDainMiller** [comment]
@dawnerd You might want to read the Trello ticket too, as I left a note about waiting until tomorrow to work on this. The only way to "test" that you search queries are working is to deploy to beta.howl.fm then test then redeploy master as quickly as you can so our private beta users don't experience pre-release features. 

@joshholat  and @jdhartley  are adding the local theme dev support for this though by tomorrow morning.

**Comment by jdhartley** [comment]
@dawnerd also note that jQuery expects `type: 'post'` and `dataType: 'json'`

**Comment by CDainMiller** [comment]
Awesome, actually no need to wait should now work on local-theme-dev. Thanks @jdhartley! cc: @dawnerd

**Comment by joshholat** [comment]
@dawnerd Also fixed the docs here: https://github.com/stagebloc/docs/commit/427304f466f979540027d97c0c5120df591c8582
